### ISSUE TITLE
Not working with ruby 2.2

### ISSUE THREAD

**Issue by Paxa** [oggy/looksee#32]
Can not compile

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/pavel/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150102-39460-aki2aj.rb extconf.rb 
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling mri/mri.c
In file included from mri/mri.c:4:
In file included from mri/2.1.0/method.h:14:
mri/2.1.0/internal.h:561:32: error: incomplete definition of type 'struct RFloat'
    return ((struct RFloat *)v)->float_value;
           ~~~~~~~~~~~~~~~~~~~~^
mri/2.1.0/internal.h:561:21: note: forward declaration of 'struct RFloat'
    return ((struct RFloat *)v)->float_value;
                    ^
1 error generated.
make: *** [mri.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/pavel/.rvm/gems/ruby-2.2.0/gems/looksee-2.1.1 for inspection.
Results logged to /Users/pavel/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-13/2.2.0-static/looksee-2.1.1/gem_make.out
An error occurred while installing looksee (2.1.1), and Bundler cannot continue.
Make sure that `gem install looksee -v '2.1.1'` succeeds before bundling.
```

**Comment by Paxa** [comment]
Thanks :+1:
